### ISSUE TITLE
闻达运行正常，但是检索数据失败

### ISSUE THREAD

**Issue by newhuman011** [AlanLee1996/wenda-webui#1]
闻达的webui本身的可以正常对话，但是这个项目的webui显示检索数据失败。
闻达终端显示：
Traceback (most recent call last):
  File "G:\ChatGLM\WENDAglm\wd-git\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\bottle.py", line 876, in _handle
    return route.call(**args)
  File "G:\ChatGLM\WENDAglm\wd-git\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "wenda.py", line 159, in api_find
    prompt = data.get('prompt')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by AlanLee1996** [comment]
闻达版本过旧，不支持api。请升级到最新版本
