### ISSUE TITLE
发不出去消息，或者提示网络错误

### ISSUE THREAD

**Issue by wwjCMP** [AlanLee1996/wenda-webui#3]
闻达能正常打开，使用本地链接提示网络错误，使用网络链接闻达输出如下错误
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\bottle.py", line 876, in _handle    return route.call(**args)
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "wenda.py", line 159, in api_find
    prompt = data.get('prompt')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by AlanLee1996** [comment]
#1 参考以前issue，闻达版本过低

**Comment by qqqkoko123** [comment]
下载了最新的闻达，还是一样报错，postman正常，应该是webui的问题

**Comment by AlanLee1996** [comment]
现在的版本应该没问题了，闻达和本项目都更新一下
